# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ds-ios' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ds-ios

  pod 'lottie-ios'

  target 'ds-iosTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ds-iosUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
